# Generated by Django 5.1.7 on 2025-04-14 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryActivityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, verbose_name='ID de session')),
                ('activity_type', models.JSONField(default=dict, verbose_name="Types d'activités pratiquées")),
                ('physical_activity_duration', models.CharField(choices=[('none', 'Aucune activité physique'), ('less_30min', 'Moins de 30 min'), ('30-60min', '30-60 min'), ('more_60min', 'Plus de 60 min')], max_length=20, verbose_name="Durée de l'activité physique")),
                ('physical_activity_frequency', models.CharField(choices=[('none', 'Jamais'), ('once', 'Une fois par semaine'), ('twice', 'Deux fois par semaine'), ('thrice', 'Trois fois par semaine'), ('more_than_thrice', 'Plus de trois fois')], max_length=20, verbose_name="Fréquence de l'activité physique")),
                ('intensity_level', models.CharField(choices=[('none', 'Non applicable'), ('low', 'Faible'), ('moderate', 'Modéré'), ('high', 'Élevé')], max_length=10, verbose_name="Niveau d’intensité de l'activité")),
                ('sleep_hours', models.CharField(choices=[('<5', 'Moins de 5 heures'), ('5-6', '5-6 heures'), ('7-8', '7-8 heures'), ('>8', 'Plus de 8 heures')], max_length=10, verbose_name='Durée du sommeil')),
                ('stress_level', models.CharField(choices=[('always', 'Tout le temps'), ('sometimes', 'Parfois'), ('rarely', 'Rarement'), ('never', 'Jamais')], max_length=20, verbose_name='Niveau de stress')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.JSONField(default=dict, verbose_name="Types d'activités pratiquées")),
                ('physical_activity_duration', models.CharField(choices=[('none', 'Aucune activité physique'), ('less_30min', 'Moins de 30 min'), ('30-60min', '30-60 min'), ('more_60min', 'Plus de 60 min')], max_length=20, verbose_name="Durée de l'activité physique")),
                ('physical_activity_frequency', models.CharField(choices=[('none', 'Jamais'), ('once', 'Une fois par semaine'), ('twice', 'Deux fois par semaine'), ('thrice', 'Trois fois par semaine'), ('more_than_thrice', 'Plus de trois fois')], max_length=20, verbose_name="Fréquence de l'activité physique")),
                ('intensity_level', models.CharField(choices=[('none', 'Non applicable'), ('low', 'Faible'), ('moderate', 'Modéré'), ('high', 'Élevé')], max_length=10, verbose_name="Niveau d’intensité de l'activité")),
                ('sleep_hours', models.CharField(choices=[('<5', 'Moins de 5 heures'), ('5-6', '5-6 heures'), ('7-8', '7-8 heures'), ('>8', 'Plus de 8 heures')], max_length=10, verbose_name='Durée du sommeil')),
                ('stress_level', models.CharField(choices=[('always', 'Tout le temps'), ('sometimes', 'Parfois'), ('rarely', 'Rarement'), ('never', 'Jamais')], max_length=20, verbose_name='Niveau de stress')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='patients.patient')),
            ],
        ),
    ]
