# Generated by Django 5.1.7 on 2025-04-14 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de l’aliment')),
                ('categorie', models.CharField(choices=[('vegetables', 'Légumes'), ('cereals', 'Céréales et Pains'), ('meat', 'Viande et Œufs'), ('fish', 'Poisson'), ('dairy', 'Produits laitiers'), ('fruits', 'Fruits et Baies'), ('other', 'Autres produits')], max_length=50, verbose_name='Catégorie')),
                ('calories', models.FloatField(verbose_name='Calories')),
                ('proteines', models.FloatField(verbose_name='Protéines')),
                ('lipides', models.FloatField(verbose_name='Lipides')),
                ('glucides', models.FloatField(verbose_name='Glucides')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryHabitudesAlimentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, verbose_name='ID de session')),
                ('eating_habits', models.JSONField(default=dict, verbose_name='Habitudes alimentaires')),
                ('meal_frequency', models.CharField(choices=[('1x', 'Une fois'), ('2x', 'Deux fois'), ('3x', 'Trois fois'), ('4x+', 'Quatre fois ou plus')], max_length=20, verbose_name='Fréquence des repas')),
                ('portion_size', models.CharField(choices=[('petite', 'Petite'), ('modérée', 'Modérée'), ('grande', 'Grande')], max_length=10, verbose_name='Taille de portion')),
                ('cooking_methods', models.JSONField(default=dict, verbose_name='Méthodes de cuisson')),
                ('water_intake', models.CharField(choices=[('less_0.5L', 'Moins de 0.5L'), ('0.5-1.5L', '0.5 - 1.5L'), ('1.5-2.5L', '1.5 - 2.5L'), ('more_2.5L', 'Plus de 2.5L')], max_length=50, verbose_name="Consommation d'eau")),
                ('diet_preferences', models.JSONField(default=dict, verbose_name='Régime alimentaire')),
                ('favorite_products', models.JSONField(default=dict, verbose_name='Produits favoris')),
            ],
        ),
        migrations.CreateModel(
            name='AlimentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutritions.aliment')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu de l’article')),
                ('date_publication', models.DateField(auto_now_add=True, verbose_name='Date de publication')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Commentaire')),
                ('date_commentaire', models.DateField(auto_now_add=True, verbose_name='Date du commentaire')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutritions.article', verbose_name='Article concerné')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'ordering': ['-date_commentaire'],
            },
        ),
        migrations.CreateModel(
            name='HabitudesAlimentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitudes', models.JSONField(default=dict, verbose_name='Habitudes alimentaires')),
                ('frequence_repas', models.CharField(choices=[('1x', 'One time'), ('2x', 'Two times'), ('3x', 'Three times'), ('4x+', 'Four times or more')], max_length=20, verbose_name='Fréquence des repas')),
                ('portion', models.CharField(choices=[('petite', 'Little'), ('modérée', 'Moderate'), ('grande', 'Large')], max_length=10, verbose_name='Taille de portion')),
                ('methode_cuisson', models.JSONField(default=dict, verbose_name='Méthodes de cuisson')),
                ('eau_consommee', models.CharField(choices=[('-0.5L', 'Less than 0.5L'), ('0.5-1.5L', '0.5 - 1.5L'), ('1.5-2.5L', '1.5 - 2.5L'), ('2.5L+', 'More than 2.5L')], max_length=20, verbose_name='Quantité d’eau consommée')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitudes_alimentaires', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PlanRepas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_plan', models.CharField(max_length=100, verbose_name='Nom du plan de repas')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description du plan')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='Dernière modification')),
                ('aliments', models.ManyToManyField(through='nutritions.AlimentPlan', to='nutritions.aliment', verbose_name='Aliments inclus')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_repas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='alimentplan',
            name='plan_repas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutritions.planrepas'),
        ),
    ]
